Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false

# Forwarding port to localhost if you want you can enable this feature
  config.vm.network "forwarded_port", guest: 3000, host: 3000

# Bridge network adapter, if you want a public network access
  config.vm.network "public_network", type: "dhcp"

# Ansible provisioner with playbook
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook/main.yml"
  end

end
